### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by DamianEdwards** [DamianEdwards/MiniValidation#11]
The name has been read as meaning "provide the minimal amount of validation". What should we rename it to? Put new suggestions in a comment by themselves and folks can vote with reactions.

Some things to keep in mind:
- There are currently two packages. The basic package containing the static `TryValidate` method, and the `.AspNetCore` package containing the `Validator<T>` class, which has a static `BindAsync` method so that `RequestDelegateFactory` will bind to it. The first package is generally usable in all .NET projects where `System.ComponentModel.DataAnnotations` validation can be used so the name should be welcoming to that, while also providing a suitable prefix for the more workload-specific package(s).
- The main call site in any project will be the call to `ProjectName.TryValidate()`, i.e. a static method on a static class. Right now the class is in the `System.ComponentModel.DataAnnotations` namespace, the same as the [in-framework `Validator` type](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator?view=net-5.0). Note that the fact the framework has a `Validator` type already is why this project doesn't use that name 😞 .

**Comment by DamianEdwards** [comment]
Project/package name: JustValidate
Type name: `JustValidate`
E.g. use: `JustValidate.Try(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
Project/package name: ValidatR
Type name: `ValidatR`
E.g. use: `ValidatR.TryValidate(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
Project/package name: Valid8
Type name: `Valid8`
E.g. use: `Valid8.TryValidate(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
Project/package name: Validation
Type name: `Validation`
E.g. use: `Validation.TryValidate(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
Project/package name: MiniValidation
Type name: `MiniValidation`
E.g. use: `MiniValidation.TryValidate(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
Project/package name: SmolValidation
Type name: `SmolValidation`
E.g. use: `SmolValidation.TryValidate(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
Project/package name: SuchValidation
Type name: `SuchValidation`
E.g. use: `SuchValidation.TryValidate(myObject, out var errors);`

**Comment by LadyNaggaga** [comment]
> Project/package name: ValidatR
> Type name: `ValidatR`
> E.g. use: `ValidatR.TryValidate(myObject, out var errors);`

When I first saw this I didn't think Validator I thought what does the R stand for

**Comment by LadyNaggaga** [comment]
> Project/package name: JustValidate
> Type name: `JustValidate`
> E.g. use: `JustValidate.Try(myObject, out var errors);`

Saw this and it was my first pick  but, on reflection I thought it sounded rude lol

**Comment by LadyNaggaga** [comment]
> Project/package name: ValidateMe
> Type name: `ValidateMe`
> E.g. use: `ValidateMe.TryValidate(myObject, out var errors);`

By far the cutest! And gives the impression that this a friendly place.

**Comment by LadyNaggaga** [comment]
> Project/package name: MiniValidation
> Type name: `MiniValidation`
> E.g. use: `MiniValidation.TryValidate(myObject, out var errors);`

Keeps in brand without implying the we are giving "minimal" validation.

**Comment by timheuer** [comment]
ValKilmer...done...consider no other options
Project/package name: ValKilmer
Type name: `ValKilmer`
E.g. use: `ValKilmer.EnsureWingman(myObject, out var errors);`

**Comment by LadyNaggaga** [comment]
> ValKilmer...done...consider no other options
> Project/package name: ValKilmer
> Type name: `ValKilmer`
> E.g. use: `ValKilmer.EnsureWingman(myObject, out var errors);`

Is this top gun reference ? lol

**Comment by DamianEdwards** [comment]
🔝 🔫

**Comment by alefranz** [comment]
sorry I'm not carrying on with the memes, but is it the _smallest, lightest, 2-in-1_ validation library?
Type name: `ValidatorGo`
E.g. use: `ValidatorGo.TryValidate(myObject, out var errors);`

**Comment by DamianEdwards** [comment]
@khalidabuhakmeh https://www.nuget.org/packages/Valkyrie

**Comment by khalidabuhakmeh** [comment]
`Valhalla` is still available. 😅

**Comment by huunab** [comment]
I actually like the current name: MinimalValidation but if that is not available my suggestion would be:

Project/package name: ComponentValidator
Type name: ComponentValidator
E.g. use: ComponentValidator.TryValidate(myObject, out var errors);

Considering the annotations are coming from `ComponentModel`

**Comment by hyrmn** [comment]
Project/package name: `MyParents`
Type name: `MyParents`
E.g. use: `MyParents.HeresWhyYouAreAFailure(myObject, out var disappointments);`

**Comment by vavjeeva** [comment]
Project/package name: MinVal
Type name: Minval
E.g. use: Minval.TryValidate(myObject, out var errors);

**Comment by hyrmn** [comment]
Project/package name: `MiniVal`
Type name: `Tri`
E.g. use: `Tri.Validate(myObject, out var errors);`

**Comment by LadyNaggaga** [comment]
MinVal made me think min value in math.

**Comment by huunab** [comment]
Or it could also be:

Project/package name: `EssentialValidator`
Type name: `EssentialValidator`
E.g. use: `EssentialValidator.TryValidate(myObject, out var errors);`

Also crazy thing: is it possible to add the `TryValidate` overload to the Validator already on the .NET via extension method?

**Comment by BoredTweak** [comment]
It feels more pragmatic to reuse the name `Validator` and instead change the namespace. Would this be too troublesome in refactoring?

Otherwise, the standalone/independent of MVC nature of the library might be the significant characteristic. Perhaps `StandaloneValidator` or `DetachedValidator`?

**Comment by DamianEdwards** [comment]
@huunab unfortunately not, it's not possible to create extension methods for static types, hence the need to come up with a type name for the method to live on. The other alternative I considered was to make the method an extension method of `object` itself, so one could do:

``` c#
app.MapPost("/widgets", (Widget widget) =>
    !widget.TryValidate(out var errors)
        ? Results.BadRequest(errors)
        : Results.Created($"/widgets/{widget.Name}", widget));
```

**Comment by DamianEdwards** [comment]
Going with `MiniValidation` for now. Thanks folks!

**Comment by DamianEdwards** [comment]
Done: https://www.nuget.org/packages/MiniValidation
